In [2]:
import pandas as pd

In [3]:
INPUT_FILE = "IE_Dataset.csv"

In [4]:
OUTPUT_CSV = "IE_Dataset_Cleaned"

In [5]:
OUTPUT_PARQUET = "pilot_bird_occurrences_clean.parquet"

In [6]:
df=pd.read_csv(INPUT_FILE, low_memory = False)

In [7]:
n_start = len(df)

In [8]:
log = []

# Removing missing/invalid coordinates

In [10]:
before = len(df)

In [11]:
df = df[df["decimalLatitude"].notna() & df["decimalLongitude"].notna()]
log.append(f"Removed {before - len(df)} records with missing latitude/longitude")

In [12]:
before =len(df)

In [13]:
df = df[df["decimalLatitude"].between(-90,90) & df["decimalLongitude"].between(-180,180) & ~((df["decimalLatitude"]==0)&(df["decimalLongitude"]==0))]

In [14]:
log.append(f"Removed {before - len(df)} records with out of range or 0,0 coordinates")

In [15]:
df.head()

,dataResourceUid,dataResourceName,images,dcterms:modified,dcterms:language,dcterms:license,rightsHolder,dcterms:accessRights,dcterms:bibliographicCitation,references,...,source,measurementID,measurementType,measurementUnit,measurementDeterminedBy,measurementAccuracy,degreeOfEstablishment,relatedResourceID,images.1,dcterms:type
0,dr1411,iNaturalist Australia,NaN,2026-08-07T05:43:07Z,NaN,CC-BY-NC 4.0 (Int),Marie Tarrant,NaN,NaN,https://www.inaturalist.org/observations/21245...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,dr29617,Xeno-canto - Bird sounds from around the world,NaN,NaN,NaN,CC-BY-NC 4.0 (Int),Nigel Jackett,NaN,NaN,https://data.biodiversitydata.nl/xeno-canto/ob...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,dr29617,Xeno-canto - Bird sounds from around the world,NaN,NaN,NaN,CC-BY-NC 4.0 (Int),Nigel Jackett,NaN,NaN,https://data.biodiversitydata.nl/xeno-canto/ob...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,dr29617,Xeno-canto - Bird sounds from around the world,NaN,NaN,NaN,CC-BY-NC 4.0 (Int),Nigel Jackett,NaN,NaN,https://data.biodiversitydata.nl/xeno-canto/ob...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,dr341,Australian National Wildlife Collection provid...,NaN,NaN,NaN,CC-BY,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Filter to Australia

In [17]:
before = len(df)

In [18]:
df = df[(df["country"] == "Australia") | (df["countryCode"] == "AU")]

In [19]:
log.append(f"Removed {before - len(df)} records not flagged as Australia")

In [20]:
df.head()

,dataResourceUid,dataResourceName,images,dcterms:modified,dcterms:language,dcterms:license,rightsHolder,dcterms:accessRights,dcterms:bibliographicCitation,references,...,source,measurementID,measurementType,measurementUnit,measurementDeterminedBy,measurementAccuracy,degreeOfEstablishment,relatedResourceID,images.1,dcterms:type
0,dr1411,iNaturalist Australia,NaN,2026-08-07T05:43:07Z,NaN,CC-BY-NC 4.0 (Int),Marie Tarrant,NaN,NaN,https://www.inaturalist.org/observations/21245...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,dr29617,Xeno-canto - Bird sounds from around the world,NaN,NaN,NaN,CC-BY-NC 4.0 (Int),Nigel Jackett,NaN,NaN,https://data.biodiversitydata.nl/xeno-canto/ob...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,dr29617,Xeno-canto - Bird sounds from around the world,NaN,NaN,NaN,CC-BY-NC 4.0 (Int),Nigel Jackett,NaN,NaN,https://data.biodiversitydata.nl/xeno-canto/ob...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,dr29617,Xeno-canto - Bird sounds from around the world,NaN,NaN,NaN,CC-BY-NC 4.0 (Int),Nigel Jackett,NaN,NaN,https://data.biodiversitydata.nl/xeno-canto/ob...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,dr341,Australian National Wildlife Collection provid...,NaN,NaN,NaN,CC-BY,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Filter to Australia's geographic bounding box

In [22]:
AUS_LAT_MIN, AUS_LAT_MAX = -44.0, -9.0
AUS_LON_MIN, AUS_LON_MAX = 112.0, 154.0

In [23]:
before = len(df)

In [24]:
df= df[df["decimalLatitude"].between(AUS_LAT_MIN, AUS_LAT_MAX) & df["decimalLongitude"].between(AUS_LON_MIN, AUS_LON_MAX)]

In [25]:
log.append(f"Removed {before -len(df)} records outside Australia bounding box" f"(lat {AUS_LAT_MIN} to {AUS_LAT_MAX}, lon {AUS_LON_MIN} to {AUS_LON_MAX})")

In [26]:
df.head()

,dataResourceUid,dataResourceName,images,dcterms:modified,dcterms:language,dcterms:license,rightsHolder,dcterms:accessRights,dcterms:bibliographicCitation,references,...,source,measurementID,measurementType,measurementUnit,measurementDeterminedBy,measurementAccuracy,degreeOfEstablishment,relatedResourceID,images.1,dcterms:type
0,dr1411,iNaturalist Australia,NaN,2026-08-07T05:43:07Z,NaN,CC-BY-NC 4.0 (Int),Marie Tarrant,NaN,NaN,https://www.inaturalist.org/observations/21245...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,dr29617,Xeno-canto - Bird sounds from around the world,NaN,NaN,NaN,CC-BY-NC 4.0 (Int),Nigel Jackett,NaN,NaN,https://data.biodiversitydata.nl/xeno-canto/ob...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,dr29617,Xeno-canto - Bird sounds from around the world,NaN,NaN,NaN,CC-BY-NC 4.0 (Int),Nigel Jackett,NaN,NaN,https://data.biodiversitydata.nl/xeno-canto/ob...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,dr29617,Xeno-canto - Bird sounds from around the world,NaN,NaN,NaN,CC-BY-NC 4.0 (Int),Nigel Jackett,NaN,NaN,https://data.biodiversitydata.nl/xeno-canto/ob...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,dr341,Australian National Wildlife Collection provid...,NaN,NaN,NaN,CC-BY,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Coordinate Uncertainity review

In [28]:
MAX_UNCERTAINTY_M = 10000

In [29]:
before = len(df)

In [30]:
df= df[ df [ "coordinateUncertaintyInMeters"].isna() | (df["coordinateUncertaintyInMeters"]<=MAX_UNCERTAINTY_M)]

In [31]:
log.append(f"Removed {before - len(df)} records with coordinateUncertaintyInMeters" f">{MAX_UNCERTAINTY_M} m")

In [32]:
missing_uncertainty = df["coordinateUncertaintyInMeters"].isna().sum()

In [33]:
generalised = df["dataGeneralizations"].notna().sum()

In [34]:
log.append(f"Note: {missing_uncertainty} remaining records have no reported" f"coordinate uncertainty (kept, flagged as unknown accuracy)")

In [35]:
log.append(f"Note: {generalised} remaining records are intentionally generalised" f"(sensitive-species location masking) - kept, flagged, not treated as error")

In [36]:
n_end=len(df)

In [37]:
print(f"Starting records: {n_start}")

Starting records: 65

In [38]:
for line in log:
    print(" -",line)

 - Removed 10 records with missing latitude/longitude
 - Removed 0 records with out of range or 0,0 coordinates
 - Removed 0 records not flagged as Australia
 - Removed 0 records outside Australia bounding box(lat -44.0 to -9.0, lon 112.0 to 154.0)
 - Removed 0 records with coordinateUncertaintyInMeters>10000 m
 - Note: 5 remaining records have no reportedcoordinate uncertainty (kept, flagged as unknown accuracy)
 - Note: 38 remaining records are intentionally generalised(sensitive-species location masking) - kept, flagged, not treated as error

In [39]:
print(f"After coordinate cleaning: {n_end} records (removed {n_start - n_end} total)")

After coordinate cleaning: 55 records (removed 10 total)

# Save the intermediate WGS84 (EPSG:4326) CSV Version

In [41]:
df.to_csv(OUTPUT_CSV, index=False)

In [42]:
print(f"Saved cleaned CSV (EPSG:4326) to {OUTPUT_CSV}")

Saved cleaned CSV (EPSG:4326) to IE_Dataset_Cleaned

# Standardise spatial reference to EPS G:3577 (GDA94/Australian Albers)

In [44]:
pip install geopandas pyproj shapely pyarrow

Requirement already satisfied: geopandas in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (1.1.4)
Requirement already satisfied: pyproj in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (3.7.2)
Requirement already satisfied: shapely in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (2.1.2)
Requirement already satisfied: pyarrow in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (25.0.1)
Requirement already satisfied: numpy>=1.24 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from geopandas) (2.5.1)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from geopandas) (0.13.0)
Requirement already satisfied: packaging in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from geopandas) (26.1)
Requirement already satisfied: pandas>=2.0.0 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from geopandas) (3.0.5)
Requirement already satisfied: certifi in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from pyproj) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [45]:
import geopandas as gpd

In [46]:
gdf = gpd.GeoDataFrame( df, geometry=gpd.points_from_xy(df["decimalLongitude"],df["decimalLatitude"]),crs="EPSG:4326",)

In [47]:
gdf_3577 = gdf.to_crs("EPSG:3577")

In [48]:
gdf_3577["easting_m"] = gdf_3577.geometry.x

In [49]:
gdf_3577["northing_m"] = gdf_3577.geometry.y

In [50]:
print(f"Reprojected {len(gdf_3577)} records from EPSG:4326 to EPSG:3577")

Reprojected 55 records from EPSG:4326 to EPSG:3577

# Export as Parquet

In [52]:
gdf_3577.to_parquet(OUTPUT_PARQUET)

In [53]:
print(f"Saved cleaned, projected dataset (EPSG:3577) to {OUTPUT_PARQUET}")

Saved cleaned, projected dataset (EPSG:3577) to pilot_bird_occurrences_clean.parquet