In [6]:
pip install elapid

Collecting elapid
  Downloading elapid-1.0.4-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: geopandas>=1.0 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from elapid) (1.1.4)
Requirement already satisfied: matplotlib>=3.10 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from elapid) (3.11.1)
Requirement already satisfied: numpy>=2.0 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from elapid) (2.5.1)
Requirement already satisfied: pandas>=2.2.2 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from elapid) (3.0.5)
Requirement already satisfied: pyproj>3.0 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from elapid) (3.7.2)
Collecting rasterio>=1.2.1 (from elapid)
  Downloading rasterio-1.5.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (8.6 kB)
Collecting rtree>=0.9 (from elapid)
  Downloading rtree-1.4.1-py3-none-macosx_11_0_arm64.whl.metadata (2.1 kB)
Requirement already satisfied: scikit-learn>=1.8 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from elapid) (1.9.0)
Requirement already satisfied: scipy>=1.13 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from elapid) (1.18.0)
Collecting tqdm>=4.60 (from elapid)
  Downloading tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: pyogrio>=0.7.2 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from geopandas>=1.0->elapid) (0.13.0)
Requirement already satisfied: packaging in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from geopandas>=1.0->elapid) (26.1)
Requirement already satisfied: shapely>=2.0.0 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from geopandas>=1.0->elapid) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from matplotlib>=3.10->elapid) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from matplotlib>=3.10->elapid) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from matplotlib>=3.10->elapid) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from matplotlib>=3.10->elapid) (1.5.0)
Requirement already satisfied: pillow>=9 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from matplotlib>=3.10->elapid) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from matplotlib>=3.10->elapid) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from matplotlib>=3.10->elapid) (2.9.0.post0)
Requirement already satisfied: certifi in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from pyogrio>=0.7.2->geopandas>=1.0->elapid) (2026.7.22)
Requirement already satisfied: six>=1.5 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.10->elapid) (1.17.0)
Collecting affine (from rasterio>=1.2.1->elapid)
  Downloading affine-3.0.1-py3-none-any.whl.metadata (4.5 kB)
Collecting attrs (from rasterio>=1.2.1->elapid)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting click!=8.2.*,>=4.0 (from rasterio>=1.2.1->elapid)
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib>=1.4.0 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from scikit-learn>=1.8->elapid) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from scikit-learn>=1.8->elapid) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /Users/missbhat/Monash/IE/Onboarding/TA27_PathEase/.conda/lib/python3.12/site-packages (from scikit-learn>=1.8->elapid) (3.6.0)
Downloading elapid-1.0.4-py3-none-any.whl (437 kB)
Downloading rasterio-1.5.1-cp312-cp312-macosx_14_0_arm64.whl (23.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 11.5 MB/s  0:00:02 eta 0:00:01
Downloading click-8.5.0-py3-none-any.whl (125 kB)
Downloading rtree-1.4.1-py3-none-macosx_11_0_arm64.whl (436 kB)
Downloading tqdm-4.70.0-py3-none-any.whl (80 kB)
Downloading affine-3.0.1-py3-none-any.whl (10 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Installing collected packages: tqdm, rtree, click, attrs, affine, rasterio, elapid
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [elapid]2m5/7 [rasterio]
Successfully installed affine-3.0.1 attrs-26.1.0 click-8.5.0 elapid-1.0.4 rasterio-1.5.1 rtree-1.4.1 tqdm-4.70.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
import numpy as np
import pandas as pd
import itertools
import warnings
from pathlib import Path
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score
import elapid as ela
import joblib

In [10]:
CSV_PATH = Path("training_matrix_with_absences.csv")

In [12]:
df=pd.read_csv(CSV_PATH)

In [14]:
df.head()

        x_coord       y_coord  presence  elevation      slope      aspect
0  9.370629e+05 -2.602305e+06         1  113.80469  12.086203  229.215260
1 -9.753301e+05 -2.762410e+06         1  524.99460  23.021828   28.830984
2 -9.753301e+05 -2.762410e+06         1  524.99460  23.021828   28.830984
3 -9.753301e+05 -2.762410e+06         1  524.99460  23.021828   28.830984
4 -1.131976e+06 -2.573076e+06         1  537.42487  18.381567    0.392016

In [16]:
aspect_rad = np.deg2rad(df["aspect"])

In [18]:
df["aspect_sin"]=np.sin(aspect_rad)

In [20]:
df["aspect_cos"]=np.cos(aspect_rad)

In [22]:
df.head()

,x_coord,y_coord,presence,elevation,slope,aspect,aspect_sin,aspect_cos
0,9.370629e+05,-2.602305e+06,1,113.80469,12.086203,229.215260,-0.757169,-0.653219
1,-9.753301e+05,-2.762410e+06,1,524.99460,23.021828,28.830984,0.482227,0.876046
2,-9.753301e+05,-2.762410e+06,1,524.99460,23.021828,28.830984,0.482227,0.876046
3,-9.753301e+05,-2.762410e+06,1,524.99460,23.021828,28.830984,0.482227,0.876046
4,-1.131976e+06,-2.573076e+06,1,537.42487,18.381567,0.392016,0.006842,0.999977

# 1. Separate unique presence and background locations

In [25]:
presence_sites = df[df["presence"] ==1].drop_duplicates (subset = ["x_coord","y_coord"])[["x_coord","y_coord","presence"]].copy()

In [27]:
background_sites = df[df["presence"]==0].drop_duplicates(subset=["x_coord","y_coord"])[["x_coord","y_coord","presence"]].copy()

# 2. Create five spatial folds based on presence locations

In [30]:
kmeans = KMeans(n_clusters = 5, n_init = 50, random_state = 1234)

In [32]:
presence_sites["fold"]=kmeans.fit_predict(presence_sites[["x_coord","y_coord"]])

# 3. Assign every background location to its nearest presence-based fold

In [35]:
background_sites["fold"] = kmeans.predict(background_sites[["x_coord","y_coord"]])

# 4. Combine the two location tables and check fold balance

In [38]:
unique_sites = pd.concat([presence_sites,background_sites],ignore_index = True)

In [42]:
fold_check=pd.crosstab(unique_sites["fold"],unique_sites["presence"])

In [44]:
fold_check.columns = ["Background(0)", "Presence (1)"]
print(fold_check)

      Background(0)  Presence (1)
fold
0                 5             6
1                20            13
2                12             6
3                12             4
4                 6             6

In [46]:
df = pd.merge(df,unique_sites [["x_coord","y_coord","fold"]],on=["x_coord","y_coord"],how="left")

In [48]:
print(pd.crosstab(df["fold"],df["presence"]))

presence   0   1
fold
0          5   8
1         20  30
2         12   7
3         12   4
4          6   6

In [50]:
FEATURES = ["elevation","slope","aspect_sin","aspect_cos"]
X,y = df[FEATURES], df["presence"]

In [52]:
def spatial_cv_splits(df,n_folds = 5):
    idx = df.index.to_numpy()
    for test_fold in range(n_folds):
        test_mask = (df["fold"] == test_fold).to_numpy()
        yield idx[~test_mask], idx[test_mask]

In [54]:
cv_splits = list(spatial_cv_splits(df))

In [56]:
logit_pipe = Pipeline([("scaler",StandardScaler()),("logistic", LogisticRegression(max_iter=2000,random_state=1234)),])

In [58]:
logit_grid={"logistic__C":[0.01,0.1,1,10,100]}

In [60]:
logit_search = GridSearchCV(logit_pipe,logit_grid,cv=cv_splits,scoring="roc_auc",n_jobs=-1)
logit_search.fit(X,y)

GridSearchCV(cv=[(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  13,  16,  17,
        18,  19,  20,  22,  23,  24,  26,  27,  28,  29,  30,  31,  32,
        33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
        46,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
        60,  61,  62,  63,  64,  66,  67,  68,  69,  71,  72,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  84,  85,  86,  87,  88,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109]),
                  array([10, 11, 12, 14, 15, 21, 25, 47, 6...
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  88,  89,  90,  94,  95,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109]),
                  array([23, 24, 32, 35, 36, 38, 68, 87, 91, 92, 93, 96]))],
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('logistic',
                                        LogisticRegression(max_iter=2000,
                                                           random_state=1234))]),
             n_jobs=-1, param_grid={'logistic__C': [0.01, 0.1, 1, 10, 100]},
             scoring='roc_auc')

In [62]:
print(f"Best params: {logit_search.best_params_}")

Best params: {'logistic__C': 0.1}

In [64]:
print(f"Best mean CV ROC-AUC: {logit_search.best_score_:.3f}")

Best mean CV ROC-AUC: 0.450

In [74]:
rf_grid = {"n_estimators": [100,200,400], "max_depth": [None,3,5,8],"min_samples_leaf": [1,2,4],"max_features": ["sqrt","log2"],}

In [78]:
rf_search =GridSearchCV(RandomForestClassifier(random_state=1234),rf_grid,cv=cv_splits, scoring="roc_auc",n_jobs = -1,)

In [80]:
rf_search.fit(X,y)

GridSearchCV(cv=[(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  13,  16,  17,
        18,  19,  20,  22,  23,  24,  26,  27,  28,  29,  30,  31,  32,
        33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,
        46,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
        60,  61,  62,  63,  64,  66,  67,  68,  69,  71,  72,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  84,  85,  86,  87,  88,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109]),
                  array([10, 11, 12, 14, 15, 21, 25, 47, 6...
        72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
        85,  86,  88,  89,  90,  94,  95,  97,  98,  99, 100, 101, 102,
       103, 104, 105, 106, 107, 108, 109]),
                  array([23, 24, 32, 35, 36, 38, 68, 87, 91, 92, 93, 96]))],
             estimator=RandomForestClassifier(random_state=1234), n_jobs=-1,
             param_grid={'max_depth': [None, 3, 5, 8],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'n_estimators': [100, 200, 400]},
             scoring='roc_auc')

In [82]:
print(f"Best params: {rf_search.best_params_}")

Best params: {'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'n_estimators': 200}

In [86]:
print(f"Best mean CV ROC-AUC: {rf_search.best_score_:.3f}")

Best mean CV ROC-AUC: 0.557